name: "tests"

on:
  push:
    branches: ["master"]
    paths:
      - ".github/**"
      - "**.py"
      - "tests/**"
  pull_request:
    branches: ["master"]
    paths:
      - ".github/**"
      - "**.py"
      - "tests/**"

jobs:
  behave:
    name: "behave tests"
    # to save resources, run only after unit tests have passed
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install packages"
        run: |
            sudo apt-get -y update
            sudo apt-get -y --no-install-recommends install podman python3-behave diffstat diffutils python3 python3-cryptography python3-pip python3-rpm python3-setuptools python3-urllib3

      - uses: actions/checkout@v3

      - name: "Run behave tests"
        run: |
          # HACK: GitHub replaces secrets with "***" in the output.
          # To avoid that, we append " #" (an empty comment) to the secret.
          # Then the resulting value won't exactly match with the secret,
          # hence it won't be sanitized.
          GHCR_USER=${{secrets.GHCR_USER}}

          if [ -z "$GHCR_USER" ]; then
            echo "GHCR_USER secret not set, skipping the job"
            exit 0;
          fi

          echo ${{secrets.GHCR_TOKEN}} | podman login ghcr.io -u "$GHCR_USER" --password-stdin

          podman pull ghcr.io/dmach/obs-server:latest

          cd behave
          behave -Dosc=../osc-wrapper.py
